name: Initialize DCGAN Model
description: Initializes the DCGAN model with support for Traditional, CAFO, and Forward Forward methods.
inputs:
  - {name: config, type: String}
outputs:
  - {name: model, type: Model}
  - {name: model_config, type: String}
implementation:
  container:
    image: gurpreetgandhi/nesy-factory:v32
    command:
      - sh
      - -c
      - |
        exec "$0" "$@"
      - python3
      - -u
      - -c
      - |
        import argparse
        import json
        import os
        import pickle
        import sys
        
        try:
            from nesy_factory.GANs import DCGAN, DCGANConfig, TrainingAlgorithm
            print("Successfully imported DCGAN from nesy_factory")
        except ImportError as e:
            print(f"Error importing from nesy_factory: {e}")
            raise

        parser = argparse.ArgumentParser()
        parser.add_argument('--config', type=str, required=True)
        parser.add_argument('--model', type=str, required=True)
        parser.add_argument('--model_config', type=str, required=True)
        args = parser.parse_args()

        config_dict = json.loads(args.config)

        print("Initializing DCGAN Model")
        
        algorithm = config_dict.get('training_algorithm', 'backprop')
        
        if algorithm == 'forward_forward':
            training_algorithm = TrainingAlgorithm.FORWARD_FORWARD
        elif algorithm == 'cascaded_forward':
            training_algorithm = TrainingAlgorithm.CASCADED_FORWARD
        else:
            training_algorithm = TrainingAlgorithm.BACKPROP
        
        dcgan_config_dict = {
            'image_size': config_dict.get('image_size', 64),
            'channels': config_dict.get('channels', 3),
            'latent_dim': config_dict.get('latent_dim', 100),
            
            'generator_layers': config_dict.get('generator_layers', [512, 256, 128, 64, 32]),
            'discriminator_layers': config_dict.get('discriminator_layers', [64, 128, 256, 512]),
            
            'training_algorithm': training_algorithm.value,
            'learning_rate': config_dict.get('learning_rate', 0.0002),
            'batch_size': config_dict.get('batch_size', 32),
            'epochs': config_dict.get('epochs', 100),
            'n_critic': config_dict.get('n_critic', 5),
            
            'use_wgan': config_dict.get('use_wgan', False),
            'use_gradient_penalty': config_dict.get('use_gradient_penalty', False),
        }
        
        dcgan_config = DCGANConfig.from_dict(dcgan_config_dict)
        
        dcgan_model = DCGAN(dcgan_config)
        
        model_wrapper = {
            'dcgan': dcgan_model,
            'config': dcgan_config.to_dict(),
            'model_type': 'DCGAN',
            'algorithm': algorithm
        }
        
        output_dir = os.path.dirname(args.model)
        if output_dir and not os.path.exists(output_dir):
            os.makedirs(output_dir, exist_ok=True)
        
        with open(args.model, "wb") as f:
            pickle.dump(model_wrapper, f)

        with open(args.model_config, "w") as f:
            f.write(json.dumps(dcgan_config.to_dict()))

        print(f"Successfully created DCGAN model")
        print(f"Training Method: {algorithm.upper()}")
        print(f"Saved DCGAN model to {args.model}")
        print(f"Saved config to {args.model_config}")
    args:
      - --config
      - {inputValue: config}
      - --model
      - {outputPath: model}
      - --model_config
      - {outputPath: model_config}
