name: Initialize DCGAN Model
description: Initializes the DCGAN model with support for Traditional, CAFO, and Forward Forward methods.
inputs:
  - {name: config, type: String}
outputs:
  - {name: model, type: Model}
  - {name: model_config_b64, type: String}
implementation:
  container:
    image: gurpreetgandhi/nesy-factory:v32
    command:
      - sh
      - -c
      - |
        exec "$0" "$@"
      - python3
      - -u
      - -c
      - |
        import argparse
        import json
        import os
        import pickle
        import sys
        import base64
        
        try:
            from nesy_factory.GANs import DCGAN, DCGANConfig, TrainingAlgorithm
            print("Successfully imported DCGAN from nesy_factory")
        except ImportError as e:
            print(f"Error importing from nesy_factory: {e}")
            raise

        parser = argparse.ArgumentParser()
        parser.add_argument('--config', type=str, required=True)
        parser.add_argument('--model', type=str, required=True)
        parser.add_argument('--model_config_b64', type=str, required=True)
        args = parser.parse_args()

        config_dict = json.loads(args.config)

        print("="*60)
        print("Initializing DCGAN Model")
        print("="*60)
        
        use_forward_forward = config_dict.get('use_forward_forward', False)
        use_cascaded_forward = config_dict.get('use_cascaded_forward', False)
        
        if use_forward_forward:
            training_algorithm = TrainingAlgorithm.FORWARD_FORWARD
        elif use_cascaded_forward:
            training_algorithm = TrainingAlgorithm.CASCADED_FORWARD
        else:
            training_algorithm = TrainingAlgorithm.BACKPROP
        
        dcgan_config_dict = {
            'image_size': config_dict.get('image_size', 64),
            'channels': config_dict.get('channels', 3),
            'latent_dim': config_dict.get('latent_dim', 100),
            
            'generator_features': config_dict.get('generator_features', 64),
            'generator_layers': config_dict.get('generator_layers', [256, 128, 64, 32]),
            'generator_activation': config_dict.get('generator_activation', 'relu'),
            'generator_output_activation': config_dict.get('generator_output_activation', 'tanh'),
            'generator_norm': config_dict.get('generator_norm', 'batch_norm'),
            
            'discriminator_features': config_dict.get('discriminator_features', 64),
            'discriminator_layers': config_dict.get('discriminator_layers', [64, 128, 256, 512]),
            'discriminator_activation': config_dict.get('discriminator_activation', 'leaky_relu'),
            'discriminator_output_activation': config_dict.get('discriminator_output_activation', 'sigmoid'),
            'discriminator_norm': config_dict.get('discriminator_norm', 'batch_norm'),
            
            'training_algorithm': training_algorithm.value,
            
            'optimizer_type': config_dict.get('optimizer_type', 'adam'),
            'learning_rate': config_dict.get('learning_rate', 0.0002),
            'beta1': config_dict.get('beta1', 0.5),
            'beta2': config_dict.get('beta2', 0.999),
            
            'batch_size': config_dict.get('batch_size', 64),
            'epochs': config_dict.get('epochs', 100),
            'n_critic': config_dict.get('n_critic', 5),
            
            'use_wgan': config_dict.get('use_wgan', False),
            'clip_value': config_dict.get('clip_value', 0.01),
            'use_gradient_penalty': config_dict.get('use_gradient_penalty', False),
            'lambda_gp': config_dict.get('lambda_gp', 10.0),
            
            'ff_theta': config_dict.get('ff_theta', 2.0),
            'ff_goodness_fn': config_dict.get('ff_goodness_fn', 'sum_squares'),
            'ff_positive_margin': config_dict.get('ff_positive_margin', 2.0),
            'ff_negative_margin': config_dict.get('ff_negative_margin', 0.0),
            
            'cafo_layers': config_dict.get('cafo_layers', 3),
            'cafo_layer_growth': config_dict.get('cafo_layer_growth', 1.5),
            
            'device': config_dict.get('device', 'auto'),
            'seed': config_dict.get('seed', 42),
            'gradient_clip': config_dict.get('gradient_clip', None),
            'label_smoothing': config_dict.get('label_smoothing', 0.1),
            
            'compute_fid': config_dict.get('compute_fid', False),
            'compute_inception_score': config_dict.get('compute_inception_score', False),
        }
        
        dcgan_config = DCGANConfig.from_dict(dcgan_config_dict)
        
        print(f"Model Architecture:")
        print(f"  Image Size: {dcgan_config.image_size}x{dcgan_config.image_size}")
        print(f"  Channels: {dcgan_config.channels}")
        print(f"  Latent Dimension: {dcgan_config.latent_dim}")
        print(f"  Training Algorithm: {dcgan_config.training_algorithm.value}")
        
        dcgan_model = DCGAN(dcgan_config)
        
        output_dir = os.path.dirname(args.model)
        if output_dir and not os.path.exists(output_dir):
            os.makedirs(output_dir, exist_ok=True)
        
        model_wrapper = {
            'dcgan': dcgan_model,
            'config': dcgan_config.to_dict(),
            'model_type': 'DCGAN',
            'training_method': dcgan_config.training_algorithm.value
        }
        
        with open(args.model, "wb") as f:
            pickle.dump(model_wrapper, f)

        config_b64 = base64.b64encode(json.dumps(dcgan_config.to_dict()).encode()).decode()
        
        with open(args.model_config_b64, "w") as f:
            f.write(config_b64)

        print("="*60)
        print(f"Successfully created DCGAN model")
        print(f"Training Method: {dcgan_config.training_algorithm.value.upper()}")
        print(f"Saved DCGAN model to {args.model}")
        print(f"Saved base64 config to {args.model_config_b64}")
        print("="*60)
    args:
      - --config
      - {inputValue: config}
      - --model
      - {outputPath: model}
      - --model_config_b64
      - {outputPath: model_config_b64}
